###########################################################################
##
##  SCM Backup
##  https://scm-backup.org/
##  Makes offline backups of your cloud hosted source code repositories
##
##  Documentation about this config file:
##  https://docs.scm-backup.org/en/latest/config.html
##
###########################################################################


# all backups go here
# localFolder: 'c:\scm-backup'

# all backups go here on docker
localFolder: '/app/backups'

# when an error occurs, wait that many seconds before exiting the application
waitSecondsOnError: 5

# uncomment this to send SCM Backup's console output via email
#email:
#  from: from@example.com
#  to: to@example.com
#  server: smtp.example.com
#  port: 0
#  useSsl: false
#  userName: testuser
#  password: not-the-real-password

sources:

  - title: citadelgroup-sydney
    hoster: bitbucket
    type: org
    name: citadelgroup-sydney
    authName: andrewlorien_citadel
    # the password is set in an environment variable which is read from an SSM parameter
    password: '%bitbucket-app-password%'


options:
    backup:
        # delete repos from local backup that don't exist at the hoster
        removeDeletedRepos : false

        # output a second log message for each repo when backing it up is finished
        logRepoFinished: true

        # add subfolder to localfolder in format yyyy-MM-dd_HHmm
        addTimestampedSubfolder: false

        # timestamp format for timestamped subfolder.
        timestampFormat: yyyy-MM-dd_HHmm

        # if this is not empty, save the files to an S3 bucket
        s3BucketName: dof-mgmt-bitbucket-backup
